name: PR title
on:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@v1.5.0
        with:
          title-regex: "^\\[(BTC-\\d+|MINOR)\\] "
          on-failed-regex-fail-action: true
          on-failed-regex-create-review: true
          on-failed-regex-request-changes: false
          on-failed-regex-comment: |
            Your Pull Request title should refer to YouTrack task by using `[BTC-<task-number>]`.
            If your task is not related to any task - use `[MINOR]` tag.
          repo-token: "${{ secrets.GITHUB_TOKEN }}"